# You'll want to customize url and baseurl for your own site:
baseurl: "/Graphic-Design-for-Science" #  the subpath of your site, e.g. /blog
url: "imnotamember.github.io" # the base hostname & protocol for your site
#remote_theme: chrisbobbe/jekyll-theme-prologue

theme: jekyll-theme-tactile
